// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: store/common.proto

// define a key package within the Boundary controller storage layer

package store

import (
	types "github.com/agile-crypto/citius-api-go/gen/go/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScopeSpecification struct {
	state              protoimpl.MessageState    `protogen:"open.v1"`
	ScopeSpecification *types.ScopeSpecification `protobuf:"bytes,3,opt,name=scope_specification,json=scopeSpecification,proto3" json:"scope_specification,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ScopeSpecification) Reset() {
	*x = ScopeSpecification{}
	mi := &file_store_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScopeSpecification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScopeSpecification) ProtoMessage() {}

func (x *ScopeSpecification) ProtoReflect() protoreflect.Message {
	mi := &file_store_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScopeSpecification.ProtoReflect.Descriptor instead.
func (*ScopeSpecification) Descriptor() ([]byte, []int) {
	return file_store_common_proto_rawDescGZIP(), []int{0}
}

func (x *ScopeSpecification) GetScopeSpecification() *types.ScopeSpecification {
	if x != nil {
		return x.ScopeSpecification
	}
	return nil
}

var File_store_common_proto protoreflect.FileDescriptor

const file_store_common_proto_rawDesc = "" +
	"\n" +
	"\x12store/common.proto\x12\x0fcaas.storage.v1\x1a\x16api/types/common.proto\"i\n" +
	"\x12ScopeSpecification\x12S\n" +
	"\x13scope_specification\x18\x03 \x01(\v2\".caas.crypto.v1.ScopeSpecificationR\x12scopeSpecificationB1Z/github.com/agile-crypto/citius-core/store;storeb\x06proto3"

var (
	file_store_common_proto_rawDescOnce sync.Once
	file_store_common_proto_rawDescData []byte
)

func file_store_common_proto_rawDescGZIP() []byte {
	file_store_common_proto_rawDescOnce.Do(func() {
		file_store_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_store_common_proto_rawDesc), len(file_store_common_proto_rawDesc)))
	})
	return file_store_common_proto_rawDescData
}

var file_store_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_store_common_proto_goTypes = []any{
	(*ScopeSpecification)(nil),       // 0: caas.storage.v1.ScopeSpecification
	(*types.ScopeSpecification)(nil), // 1: caas.crypto.v1.ScopeSpecification
}
var file_store_common_proto_depIdxs = []int32{
	1, // 0: caas.storage.v1.ScopeSpecification.scope_specification:type_name -> caas.crypto.v1.ScopeSpecification
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_store_common_proto_init() }
func file_store_common_proto_init() {
	if File_store_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_store_common_proto_rawDesc), len(file_store_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_store_common_proto_goTypes,
		DependencyIndexes: file_store_common_proto_depIdxs,
		MessageInfos:      file_store_common_proto_msgTypes,
	}.Build()
	File_store_common_proto = out.File
	file_store_common_proto_goTypes = nil
	file_store_common_proto_depIdxs = nil
}
