// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: store/key.proto

package store

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	types "github.com/agile-crypto/citius-api-go/gen/go/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyVersionStatus int32

const (
	KeyVersionStatus_KEY_VERSION_STATUS_UNSPECIFIED KeyVersionStatus = 0
	KeyVersionStatus_KEY_VERSION_STATUS_ACTIVE      KeyVersionStatus = 1
	KeyVersionStatus_KEY_VERSION_STATUS_INACTIVE    KeyVersionStatus = 2
	KeyVersionStatus_KEY_VERSION_STATUS_DESTROYED   KeyVersionStatus = 3
)

// Enum value maps for KeyVersionStatus.
var (
	KeyVersionStatus_name = map[int32]string{
		0: "KEY_VERSION_STATUS_UNSPECIFIED",
		1: "KEY_VERSION_STATUS_ACTIVE",
		2: "KEY_VERSION_STATUS_INACTIVE",
		3: "KEY_VERSION_STATUS_DESTROYED",
	}
	KeyVersionStatus_value = map[string]int32{
		"KEY_VERSION_STATUS_UNSPECIFIED": 0,
		"KEY_VERSION_STATUS_ACTIVE":      1,
		"KEY_VERSION_STATUS_INACTIVE":    2,
		"KEY_VERSION_STATUS_DESTROYED":   3,
	}
)

func (x KeyVersionStatus) Enum() *KeyVersionStatus {
	p := new(KeyVersionStatus)
	*p = x
	return p
}

func (x KeyVersionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyVersionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_store_key_proto_enumTypes[0].Descriptor()
}

func (KeyVersionStatus) Type() protoreflect.EnumType {
	return &file_store_key_proto_enumTypes[0]
}

func (x KeyVersionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyVersionStatus.Descriptor instead.
func (KeyVersionStatus) EnumDescriptor() ([]byte, []int) {
	return file_store_key_proto_rawDescGZIP(), []int{0}
}

// KeyVersion represents a version of a key with its material
type KeyVersion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: gorm:"primary_key"
	PublicId string `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	// version number
	// @gotags: gorm:"not_null;uniqueIndex:key_version_idx"
	Version uint32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	// the public id of the key to which this version belongs
	// @gotags: gorm:"not_null,index;uniqueIndex:key_version_idx"
	KeyId string `protobuf:"bytes,3,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// @gotags: gorm:"default:current_timestamp"
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// @gotags: gorm:"default:current_timestamp"
	UpdateTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	// ciphertext key material stored in the database
	// @gotags: gorm:"column:key_material;not_null" wrapping:"ct,key_material"
	CtKeyMaterial []byte `protobuf:"bytes,6,opt,name=ct_key_material,json=ctKeyMaterial,proto3" json:"ct_key_material,omitempty"`
	// plain text version of the decrypted key material
	// we are NOT storing this plain-text key material in the db
	// @gotags: gorm:"-" wrapping:"pt,key_material"
	KeyMaterial []byte `protobuf:"bytes,7,opt,name=key_material,json=keyMaterial,proto3" json:"key_material,omitempty"`
	// Template associated with the key material
	// @gotags: gorm:"not_null"
	TemplateId string `protobuf:"bytes,8,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	// digest used for integrity checks
	// @gotags: gorm:"not_null"
	Digest []byte `protobuf:"bytes,9,opt,name=digest,proto3" json:"digest,omitempty"`
	// digest algorithm used to calculate the digest
	// @gotags: gorm:"not_null"
	DigestAlgorithm string `protobuf:"bytes,10,opt,name=digest_algorithm,json=digestAlgorithm,proto3" json:"digest_algorithm,omitempty"`
	// id of the key used to encrypt the key material
	// @gotags: gorm:"not_null"
	WrappingKeyId string `protobuf:"bytes,11,opt,name=wrapping_key_id,json=wrappingKeyId,proto3" json:"wrapping_key_id,omitempty"`
	// id of the provider where the key lives
	// @gotags: gorm:"not_null"
	ProviderId string `protobuf:"bytes,12,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	// Lifecycle state of the key version
	// @gotags: gorm:"not_null"
	State types.KeyLifecycleState `protobuf:"varint,13,opt,name=state,proto3,enum=caas.crypto.v1.KeyLifecycleState" json:"state,omitempty"`
	// Scope and filtering properties effective for this key version
	// @gotags: gorm:"not_null"
	ScopeSpecification []byte `protobuf:"bytes,14,opt,name=scope_specification,json=scopeSpecification,proto3" json:"scope_specification,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *KeyVersion) Reset() {
	*x = KeyVersion{}
	mi := &file_store_key_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyVersion) ProtoMessage() {}

func (x *KeyVersion) ProtoReflect() protoreflect.Message {
	mi := &file_store_key_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyVersion.ProtoReflect.Descriptor instead.
func (*KeyVersion) Descriptor() ([]byte, []int) {
	return file_store_key_proto_rawDescGZIP(), []int{0}
}

func (x *KeyVersion) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *KeyVersion) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *KeyVersion) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *KeyVersion) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *KeyVersion) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *KeyVersion) GetCtKeyMaterial() []byte {
	if x != nil {
		return x.CtKeyMaterial
	}
	return nil
}

func (x *KeyVersion) GetKeyMaterial() []byte {
	if x != nil {
		return x.KeyMaterial
	}
	return nil
}

func (x *KeyVersion) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *KeyVersion) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *KeyVersion) GetDigestAlgorithm() string {
	if x != nil {
		return x.DigestAlgorithm
	}
	return ""
}

func (x *KeyVersion) GetWrappingKeyId() string {
	if x != nil {
		return x.WrappingKeyId
	}
	return ""
}

func (x *KeyVersion) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *KeyVersion) GetState() types.KeyLifecycleState {
	if x != nil {
		return x.State
	}
	return types.KeyLifecycleState(0)
}

func (x *KeyVersion) GetScopeSpecification() []byte {
	if x != nil {
		return x.ScopeSpecification
	}
	return nil
}

// Key represents a cryptographic key stored in the database
type Key struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: gorm:"primary_key"
	PublicId string `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	// @gotags: gorm:"not_null"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// @gotags: gorm:"default:current_timestamp"
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// @gotags: gorm:"default:current_timestamp"
	UpdateTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	// @gotags: gorm:"default:null"
	DestroyTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=destroy_time,json=destroyTime,proto3" json:"destroy_time,omitempty"`
	// @gotags: gorm:"not_null"
	Primitive string `protobuf:"bytes,6,opt,name=primitive,proto3" json:"primitive,omitempty"`
	// @gotags: gorm:"not_null"
	PolicyId string `protobuf:"bytes,8,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	// id of the current version of the key
	// @gotags: gorm:"not_null"
	CurrentVersion uint32 `protobuf:"varint,9,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	// Labels associated with the key
	Labels        map[string]string       `protobuf:"bytes,10,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	State         types.KeyLifecycleState `protobuf:"varint,11,opt,name=state,proto3,enum=caas.crypto.v1.KeyLifecycleState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Key) Reset() {
	*x = Key{}
	mi := &file_store_key_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_store_key_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_store_key_proto_rawDescGZIP(), []int{1}
}

func (x *Key) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *Key) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Key) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Key) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *Key) GetDestroyTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DestroyTime
	}
	return nil
}

func (x *Key) GetPrimitive() string {
	if x != nil {
		return x.Primitive
	}
	return ""
}

func (x *Key) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *Key) GetCurrentVersion() uint32 {
	if x != nil {
		return x.CurrentVersion
	}
	return 0
}

func (x *Key) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Key) GetState() types.KeyLifecycleState {
	if x != nil {
		return x.State
	}
	return types.KeyLifecycleState(0)
}

var File_store_key_proto protoreflect.FileDescriptor

const file_store_key_proto_rawDesc = "" +
	"\n" +
	"\x0fstore/key.proto\x12\x0fcaas.storage.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16api/types/common.proto\x1a\x1bbuf/validate/validate.proto\"\xf5\x04\n" +
	"\n" +
	"KeyVersion\x12*\n" +
	"\tpublic_id\x18\x01 \x01(\tB\r\xbaH\n" +
	"r\b\x10\x05:\x04ver_R\bpublicId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\x12$\n" +
	"\x06key_id\x18\x03 \x01(\tB\r\xbaH\n" +
	"r\b\x10\x05:\x04key_R\x05keyId\x12;\n" +
	"\vcreate_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x12&\n" +
	"\x0fct_key_material\x18\x06 \x01(\fR\rctKeyMaterial\x12!\n" +
	"\fkey_material\x18\a \x01(\fR\vkeyMaterial\x12\x1f\n" +
	"\vtemplate_id\x18\b \x01(\tR\n" +
	"templateId\x12\x16\n" +
	"\x06digest\x18\t \x01(\fR\x06digest\x12)\n" +
	"\x10digest_algorithm\x18\n" +
	" \x01(\tR\x0fdigestAlgorithm\x128\n" +
	"\x0fwrapping_key_id\x18\v \x01(\tB\x10\xbaH\r\xd8\x01\x01r\b\x10\x05:\x04key_R\rwrappingKeyId\x12.\n" +
	"\vprovider_id\x18\f \x01(\tB\r\xbaH\n" +
	"r\b\x10\x05:\x04prv_R\n" +
	"providerId\x127\n" +
	"\x05state\x18\r \x01(\x0e2!.caas.crypto.v1.KeyLifecycleStateR\x05state\x12/\n" +
	"\x13scope_specification\x18\x0e \x01(\fR\x12scopeSpecification\"\xb4\x04\n" +
	"\x03Key\x12*\n" +
	"\tpublic_id\x18\x01 \x01(\tB\r\xbaH\n" +
	"r\b\x10\x05:\x04key_R\bpublicId\x12\x1e\n" +
	"\x04name\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x02R\x04name\x12;\n" +
	"\vcreate_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x12=\n" +
	"\fdestroy_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vdestroyTime\x12\x1c\n" +
	"\tprimitive\x18\x06 \x01(\tR\tprimitive\x12*\n" +
	"\tpolicy_id\x18\b \x01(\tB\r\xbaH\n" +
	"r\b\x10\x05:\x04pol_R\bpolicyId\x120\n" +
	"\x0fcurrent_version\x18\t \x01(\rB\a\xbaH\x04*\x02(\x01R\x0ecurrentVersion\x128\n" +
	"\x06labels\x18\n" +
	" \x03(\v2 .caas.storage.v1.Key.LabelsEntryR\x06labels\x127\n" +
	"\x05state\x18\v \x01(\x0e2!.caas.crypto.v1.KeyLifecycleStateR\x05state\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x98\x01\n" +
	"\x10KeyVersionStatus\x12\"\n" +
	"\x1eKEY_VERSION_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19KEY_VERSION_STATUS_ACTIVE\x10\x01\x12\x1f\n" +
	"\x1bKEY_VERSION_STATUS_INACTIVE\x10\x02\x12 \n" +
	"\x1cKEY_VERSION_STATUS_DESTROYED\x10\x03B1Z/github.com/agile-crypto/citius-core/store;storeb\x06proto3"

var (
	file_store_key_proto_rawDescOnce sync.Once
	file_store_key_proto_rawDescData []byte
)

func file_store_key_proto_rawDescGZIP() []byte {
	file_store_key_proto_rawDescOnce.Do(func() {
		file_store_key_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_store_key_proto_rawDesc), len(file_store_key_proto_rawDesc)))
	})
	return file_store_key_proto_rawDescData
}

var file_store_key_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_store_key_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_store_key_proto_goTypes = []any{
	(KeyVersionStatus)(0),         // 0: caas.storage.v1.KeyVersionStatus
	(*KeyVersion)(nil),            // 1: caas.storage.v1.KeyVersion
	(*Key)(nil),                   // 2: caas.storage.v1.Key
	nil,                           // 3: caas.storage.v1.Key.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(types.KeyLifecycleState)(0),  // 5: caas.crypto.v1.KeyLifecycleState
}
var file_store_key_proto_depIdxs = []int32{
	4, // 0: caas.storage.v1.KeyVersion.create_time:type_name -> google.protobuf.Timestamp
	4, // 1: caas.storage.v1.KeyVersion.update_time:type_name -> google.protobuf.Timestamp
	5, // 2: caas.storage.v1.KeyVersion.state:type_name -> caas.crypto.v1.KeyLifecycleState
	4, // 3: caas.storage.v1.Key.create_time:type_name -> google.protobuf.Timestamp
	4, // 4: caas.storage.v1.Key.update_time:type_name -> google.protobuf.Timestamp
	4, // 5: caas.storage.v1.Key.destroy_time:type_name -> google.protobuf.Timestamp
	3, // 6: caas.storage.v1.Key.labels:type_name -> caas.storage.v1.Key.LabelsEntry
	5, // 7: caas.storage.v1.Key.state:type_name -> caas.crypto.v1.KeyLifecycleState
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_store_key_proto_init() }
func file_store_key_proto_init() {
	if File_store_key_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_store_key_proto_rawDesc), len(file_store_key_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_store_key_proto_goTypes,
		DependencyIndexes: file_store_key_proto_depIdxs,
		EnumInfos:         file_store_key_proto_enumTypes,
		MessageInfos:      file_store_key_proto_msgTypes,
	}.Build()
	File_store_key_proto = out.File
	file_store_key_proto_goTypes = nil
	file_store_key_proto_depIdxs = nil
}
