// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: store/policy.proto

package store

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PolicyScope controls which operations a policy governs.
type PolicyScope int32

const (
	PolicyScope_POLICY_SCOPE_UNSPECIFIED PolicyScope = 0
	PolicyScope_POLICY_SCOPE_GLOBAL      PolicyScope = 1
	PolicyScope_POLICY_SCOPE_KEY         PolicyScope = 2
	PolicyScope_POLICY_SCOPE_OPERATION   PolicyScope = 3
)

// Enum value maps for PolicyScope.
var (
	PolicyScope_name = map[int32]string{
		0: "POLICY_SCOPE_UNSPECIFIED",
		1: "POLICY_SCOPE_GLOBAL",
		2: "POLICY_SCOPE_KEY",
		3: "POLICY_SCOPE_OPERATION",
	}
	PolicyScope_value = map[string]int32{
		"POLICY_SCOPE_UNSPECIFIED": 0,
		"POLICY_SCOPE_GLOBAL":      1,
		"POLICY_SCOPE_KEY":         2,
		"POLICY_SCOPE_OPERATION":   3,
	}
)

func (x PolicyScope) Enum() *PolicyScope {
	p := new(PolicyScope)
	*p = x
	return p
}

func (x PolicyScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PolicyScope) Descriptor() protoreflect.EnumDescriptor {
	return file_store_policy_proto_enumTypes[0].Descriptor()
}

func (PolicyScope) Type() protoreflect.EnumType {
	return &file_store_policy_proto_enumTypes[0]
}

func (x PolicyScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PolicyScope.Descriptor instead.
func (PolicyScope) EnumDescriptor() ([]byte, []int) {
	return file_store_policy_proto_rawDescGZIP(), []int{0}
}

// StoredPolicy is the persisted representation of an access-control + algorithm policy.
type StoredPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicId      string                 `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Scope         PolicyScope            `protobuf:"varint,3,opt,name=scope,proto3,enum=caas.storage.v1.PolicyScope" json:"scope,omitempty"`
	RulesJson     []byte                 `protobuf:"bytes,4,opt,name=rules_json,json=rulesJson,proto3" json:"rules_json,omitempty"` // opaque JSON blob — parsed by policy core
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoredPolicy) Reset() {
	*x = StoredPolicy{}
	mi := &file_store_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoredPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredPolicy) ProtoMessage() {}

func (x *StoredPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_store_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredPolicy.ProtoReflect.Descriptor instead.
func (*StoredPolicy) Descriptor() ([]byte, []int) {
	return file_store_policy_proto_rawDescGZIP(), []int{0}
}

func (x *StoredPolicy) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *StoredPolicy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StoredPolicy) GetScope() PolicyScope {
	if x != nil {
		return x.Scope
	}
	return PolicyScope_POLICY_SCOPE_UNSPECIFIED
}

func (x *StoredPolicy) GetRulesJson() []byte {
	if x != nil {
		return x.RulesJson
	}
	return nil
}

func (x *StoredPolicy) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StoredPolicy) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *StoredPolicy) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *StoredPolicy) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

var File_store_policy_proto protoreflect.FileDescriptor

const file_store_policy_proto_rawDesc = "" +
	"\n" +
	"\x12store/policy.proto\x12\x0fcaas.storage.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"\xbf\x03\n" +
	"\fStoredPolicy\x12*\n" +
	"\tpublic_id\x18\x01 \x01(\tB\r\xbaH\n" +
	"r\b\x10\x05:\x04pol_R\bpublicId\x12\x1e\n" +
	"\x04name\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x02R\x04name\x122\n" +
	"\x05scope\x18\x03 \x01(\x0e2\x1c.caas.storage.v1.PolicyScopeR\x05scope\x12\x1d\n" +
	"\n" +
	"rules_json\x18\x04 \x01(\fR\trulesJson\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12;\n" +
	"\vcreate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x12A\n" +
	"\x06labels\x18\b \x03(\v2).caas.storage.v1.StoredPolicy.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*v\n" +
	"\vPolicyScope\x12\x1c\n" +
	"\x18POLICY_SCOPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13POLICY_SCOPE_GLOBAL\x10\x01\x12\x14\n" +
	"\x10POLICY_SCOPE_KEY\x10\x02\x12\x1a\n" +
	"\x16POLICY_SCOPE_OPERATION\x10\x03B1Z/github.com/agile-crypto/citius-core/store;storeb\x06proto3"

var (
	file_store_policy_proto_rawDescOnce sync.Once
	file_store_policy_proto_rawDescData []byte
)

func file_store_policy_proto_rawDescGZIP() []byte {
	file_store_policy_proto_rawDescOnce.Do(func() {
		file_store_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_store_policy_proto_rawDesc), len(file_store_policy_proto_rawDesc)))
	})
	return file_store_policy_proto_rawDescData
}

var file_store_policy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_store_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_store_policy_proto_goTypes = []any{
	(PolicyScope)(0),              // 0: caas.storage.v1.PolicyScope
	(*StoredPolicy)(nil),          // 1: caas.storage.v1.StoredPolicy
	nil,                           // 2: caas.storage.v1.StoredPolicy.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_store_policy_proto_depIdxs = []int32{
	0, // 0: caas.storage.v1.StoredPolicy.scope:type_name -> caas.storage.v1.PolicyScope
	3, // 1: caas.storage.v1.StoredPolicy.create_time:type_name -> google.protobuf.Timestamp
	3, // 2: caas.storage.v1.StoredPolicy.update_time:type_name -> google.protobuf.Timestamp
	2, // 3: caas.storage.v1.StoredPolicy.labels:type_name -> caas.storage.v1.StoredPolicy.LabelsEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_store_policy_proto_init() }
func file_store_policy_proto_init() {
	if File_store_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_store_policy_proto_rawDesc), len(file_store_policy_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_store_policy_proto_goTypes,
		DependencyIndexes: file_store_policy_proto_depIdxs,
		EnumInfos:         file_store_policy_proto_enumTypes,
		MessageInfos:      file_store_policy_proto_msgTypes,
	}.Build()
	File_store_policy_proto = out.File
	file_store_policy_proto_goTypes = nil
	file_store_policy_proto_depIdxs = nil
}
