// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: store/provider_instance.proto

package store

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StoredProviderInstance is the persisted configuration for one registered provider.
type StoredProviderInstance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicId      string                 `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ProviderType  string                 `protobuf:"bytes,3,opt,name=provider_type,json=providerType,proto3" json:"provider_type,omitempty"` // "software", "hsm", ...
	ConfigJson    []byte                 `protobuf:"bytes,4,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`       // opaque provider-specific config
	IsDefault     bool                   `protobuf:"varint,5,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoredProviderInstance) Reset() {
	*x = StoredProviderInstance{}
	mi := &file_store_provider_instance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoredProviderInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredProviderInstance) ProtoMessage() {}

func (x *StoredProviderInstance) ProtoReflect() protoreflect.Message {
	mi := &file_store_provider_instance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredProviderInstance.ProtoReflect.Descriptor instead.
func (*StoredProviderInstance) Descriptor() ([]byte, []int) {
	return file_store_provider_instance_proto_rawDescGZIP(), []int{0}
}

func (x *StoredProviderInstance) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *StoredProviderInstance) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StoredProviderInstance) GetProviderType() string {
	if x != nil {
		return x.ProviderType
	}
	return ""
}

func (x *StoredProviderInstance) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

func (x *StoredProviderInstance) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *StoredProviderInstance) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *StoredProviderInstance) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

var File_store_provider_instance_proto protoreflect.FileDescriptor

const file_store_provider_instance_proto_rawDesc = "" +
	"\n" +
	"\x1dstore/provider_instance.proto\x12\x0fcaas.storage.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"\xce\x02\n" +
	"\x16StoredProviderInstance\x12*\n" +
	"\tpublic_id\x18\x01 \x01(\tB\r\xbaH\n" +
	"r\b\x10\x05:\x04prv_R\bpublicId\x12\x1e\n" +
	"\x04name\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x02R\x04name\x12.\n" +
	"\rprovider_type\x18\x03 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18@R\fproviderType\x12\x1f\n" +
	"\vconfig_json\x18\x04 \x01(\fR\n" +
	"configJson\x12\x1d\n" +
	"\n" +
	"is_default\x18\x05 \x01(\bR\tisDefault\x12;\n" +
	"\vcreate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTimeB1Z/github.com/agile-crypto/citius-core/store;storeb\x06proto3"

var (
	file_store_provider_instance_proto_rawDescOnce sync.Once
	file_store_provider_instance_proto_rawDescData []byte
)

func file_store_provider_instance_proto_rawDescGZIP() []byte {
	file_store_provider_instance_proto_rawDescOnce.Do(func() {
		file_store_provider_instance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_store_provider_instance_proto_rawDesc), len(file_store_provider_instance_proto_rawDesc)))
	})
	return file_store_provider_instance_proto_rawDescData
}

var file_store_provider_instance_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_store_provider_instance_proto_goTypes = []any{
	(*StoredProviderInstance)(nil), // 0: caas.storage.v1.StoredProviderInstance
	(*timestamppb.Timestamp)(nil),  // 1: google.protobuf.Timestamp
}
var file_store_provider_instance_proto_depIdxs = []int32{
	1, // 0: caas.storage.v1.StoredProviderInstance.create_time:type_name -> google.protobuf.Timestamp
	1, // 1: caas.storage.v1.StoredProviderInstance.update_time:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_store_provider_instance_proto_init() }
func file_store_provider_instance_proto_init() {
	if File_store_provider_instance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_store_provider_instance_proto_rawDesc), len(file_store_provider_instance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_store_provider_instance_proto_goTypes,
		DependencyIndexes: file_store_provider_instance_proto_depIdxs,
		MessageInfos:      file_store_provider_instance_proto_msgTypes,
	}.Build()
	File_store_provider_instance_proto = out.File
	file_store_provider_instance_proto_goTypes = nil
	file_store_provider_instance_proto_depIdxs = nil
}
