// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: store/session.proto

package store

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SessionStatus represents the lifecycle state of a multi-part session.
type SessionStatus int32

const (
	SessionStatus_SESSION_STATUS_UNSPECIFIED SessionStatus = 0
	SessionStatus_SESSION_STATUS_ACTIVE      SessionStatus = 1
	SessionStatus_SESSION_STATUS_FINALISED   SessionStatus = 2
	SessionStatus_SESSION_STATUS_EXPIRED     SessionStatus = 3
)

// Enum value maps for SessionStatus.
var (
	SessionStatus_name = map[int32]string{
		0: "SESSION_STATUS_UNSPECIFIED",
		1: "SESSION_STATUS_ACTIVE",
		2: "SESSION_STATUS_FINALISED",
		3: "SESSION_STATUS_EXPIRED",
	}
	SessionStatus_value = map[string]int32{
		"SESSION_STATUS_UNSPECIFIED": 0,
		"SESSION_STATUS_ACTIVE":      1,
		"SESSION_STATUS_FINALISED":   2,
		"SESSION_STATUS_EXPIRED":     3,
	}
)

func (x SessionStatus) Enum() *SessionStatus {
	p := new(SessionStatus)
	*p = x
	return p
}

func (x SessionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_store_session_proto_enumTypes[0].Descriptor()
}

func (SessionStatus) Type() protoreflect.EnumType {
	return &file_store_session_proto_enumTypes[0]
}

func (x SessionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionStatus.Descriptor instead.
func (SessionStatus) EnumDescriptor() ([]byte, []int) {
	return file_store_session_proto_rawDescGZIP(), []int{0}
}

// StoredSession holds the state for a multi-part streaming operation.
type StoredSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicId      string                 `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Operation     string                 `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"` // "sign", "verify", "encrypt", "decrypt"
	State         []byte                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`         // provider-specific serialised state
	Status        SessionStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=caas.storage.v1.SessionStatus" json:"status,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	ExpireTime    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoredSession) Reset() {
	*x = StoredSession{}
	mi := &file_store_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoredSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredSession) ProtoMessage() {}

func (x *StoredSession) ProtoReflect() protoreflect.Message {
	mi := &file_store_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredSession.ProtoReflect.Descriptor instead.
func (*StoredSession) Descriptor() ([]byte, []int) {
	return file_store_session_proto_rawDescGZIP(), []int{0}
}

func (x *StoredSession) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *StoredSession) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *StoredSession) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *StoredSession) GetState() []byte {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *StoredSession) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

func (x *StoredSession) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *StoredSession) GetExpireTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireTime
	}
	return nil
}

var File_store_session_proto protoreflect.FileDescriptor

const file_store_session_proto_rawDesc = "" +
	"\n" +
	"\x13store/session.proto\x12\x0fcaas.storage.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"\xd2\x02\n" +
	"\rStoredSession\x12*\n" +
	"\tpublic_id\x18\x01 \x01(\tB\r\xbaH\n" +
	"r\b\x10\x05:\x04ses_R\bpublicId\x12$\n" +
	"\x06key_id\x18\x02 \x01(\tB\r\xbaH\n" +
	"r\b\x10\x05:\x04key_R\x05keyId\x12'\n" +
	"\toperation\x18\x03 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18@R\toperation\x12\x14\n" +
	"\x05state\x18\x04 \x01(\fR\x05state\x126\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1e.caas.storage.v1.SessionStatusR\x06status\x12;\n" +
	"\vcreate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vexpire_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expireTime*\x84\x01\n" +
	"\rSessionStatus\x12\x1e\n" +
	"\x1aSESSION_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SESSION_STATUS_ACTIVE\x10\x01\x12\x1c\n" +
	"\x18SESSION_STATUS_FINALISED\x10\x02\x12\x1a\n" +
	"\x16SESSION_STATUS_EXPIRED\x10\x03B1Z/github.com/agile-crypto/citius-core/store;storeb\x06proto3"

var (
	file_store_session_proto_rawDescOnce sync.Once
	file_store_session_proto_rawDescData []byte
)

func file_store_session_proto_rawDescGZIP() []byte {
	file_store_session_proto_rawDescOnce.Do(func() {
		file_store_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_store_session_proto_rawDesc), len(file_store_session_proto_rawDesc)))
	})
	return file_store_session_proto_rawDescData
}

var file_store_session_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_store_session_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_store_session_proto_goTypes = []any{
	(SessionStatus)(0),            // 0: caas.storage.v1.SessionStatus
	(*StoredSession)(nil),         // 1: caas.storage.v1.StoredSession
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_store_session_proto_depIdxs = []int32{
	0, // 0: caas.storage.v1.StoredSession.status:type_name -> caas.storage.v1.SessionStatus
	2, // 1: caas.storage.v1.StoredSession.create_time:type_name -> google.protobuf.Timestamp
	2, // 2: caas.storage.v1.StoredSession.expire_time:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_store_session_proto_init() }
func file_store_session_proto_init() {
	if File_store_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_store_session_proto_rawDesc), len(file_store_session_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_store_session_proto_goTypes,
		DependencyIndexes: file_store_session_proto_depIdxs,
		EnumInfos:         file_store_session_proto_enumTypes,
		MessageInfos:      file_store_session_proto_msgTypes,
	}.Build()
	File_store_session_proto = out.File
	file_store_session_proto_goTypes = nil
	file_store_session_proto_depIdxs = nil
}
